config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  root  to: 'site#index'
  resources :movies

  
  get '/site/genre/:genre', to: 'site#genre'
  get '/site/releases', to: 'site#release'
  get '/site/wanted', to: 'site#wanted'
  get '/search', to: 'site#search'
  get '/book/:id', to: 'site#book'
  post '/booking',  to: 'booking#create'
  get '/booking/show', to: 'booking#show'
  #post '/search', to: 'site#search'

  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
  end

  # GET /movies/new
  def new
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :running_time, :synopsis, :section, :direction, :cast, :status)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<div class="container">
  <div class="col-md-9">  

<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Titulo" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Genero" %>
    <%= form.text_field :genre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Duração" %>
    <%= form.number_field :running_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Sinopse" %>
    <%= form.text_field :synopsis, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Direção" %>
    <%= form.text_field :direction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "elenco" %>
    <%= form.text_field :cast, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar", class: 'btn btn-primary' %>
  </div>
<% end %>

  </div>

</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie, class: 'btn btn-info' %> |
<%= link_to 'Back', movies_path, class: 'btn btn-info' %>

app/views/movies/index.html.erb
<div class="cointainer-fluid">
  <div class="row-fluid">
<h1>Filmes</h1>

<%= link_to 'Cadastrar', new_movie_path, class: 'btn btn-primary' %>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr class="row">
      <th scope="col">Titulo</th>
      <th scope="col">Gênero</th>
      <th scope="col">Duração</th>
      <th scope="col">Sinopse</th>
      <th scope="col">Direção</th>
      <th scope="col">Elenco</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr class="row">
        <td><%= movie.title %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.running_time %></td>
        <td><%= movie.synopsis %></td>
        <td><%= movie.direction %></td>
        <td><%= movie.cast %></td>
        <td><%= movie.status %></td>
        <td><%= link_to 'Exibir', movie ,  class: "btn btn-info"  %></td>
        <td><%= link_to 'Editar', edit_movie_path(movie),  class: "btn btn-info"  %></td>
        <td><%= link_to 'Excluir', movie, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-info"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 </div>
</div>

app/views/movies/new.html.erb
<h1>Novo Filme </h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path, class: 'btn btn-info' %>

app/views/movies/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Duração:</strong>
  <%= @movie.running_time %>
</p>

<p>
  <strong>Sinopse:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Direção:</strong>
  <%= @movie.direction %>
</p>

<p>
  <strong>Elenco:</strong>
  <%= @movie.cast %>
</p>

<p>
  <strong>Status:</strong>
  <%= @movie.status %>
</p>

<%= link_to 'Editar', edit_movie_path(@movie), class: 'btn btn-info' %> |
<%= link_to 'Voltar', movies_path, class: 'btn btn-info' %>