config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  root  to: 'site#index'
  resources :movies

  
  get '/site/genre/:genre', to: 'site#genre'
  get '/site/releases', to: 'site#release'
  get '/site/wanted', to: 'site#wanted'
  get '/search', to: 'site#search'
  get '/book/:id', to: 'site#book'
  post '/booking',  to: 'booking#create'
  get '/booking/show', to: 'booking#show'
  #post '/search', to: 'site#search'

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, through: :movie_users

  validates :name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}
  VALID_EMAIL_FORMAT= /\S+@\w+\.\w{2,6}(\.\w{2})?/
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  VALID_PHONE_FORMAT= /(\(\d{2}\)\s?)?\d{4,5}-\d{4}/
  validates :phone, presence: true, format: {with: VALID_PHONE_FORMAT}
  before_save { self.email = email.downcase }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @user = current_user
    redirect_to root_path, alert: "Você não tem acesso a esse conteúdo" unless @user.admin?
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end
 

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'usuario foi alterado com sucesso' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :address, :password, :password_confirmation, :email)
    end
end

app/views/users/index.html.erb
<div class="cointainer-fluid">
  <div class="row-fluid">
    
<h1>Usuários</h1>

<%= link_to 'Novo Usuário', new_user_registration_path, class: "btn btn-primary" %>


<table class="table table-hover">
  <thead class="thead-dark">
    <tr class="row">
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Telefone</th>
      <th scope="col">Endereço</th>
      <th scope="col" colspan="3"></th>x
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="row">
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user,  class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),  class: "btn btn-info"  %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-info"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>





 </div>
</div>

app/views/users/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.genre %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @user.running_time %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @user.synopsis %>
</p>



<%= link_to 'Editar', edit_user_path(@user), class: 'btn btn-primary' %> |
<%= link_to 'Voltar', users_path, class: 'btn btn-info' %>